FROM dpage/pgadmin4
# Set environmental variables for the login
# Warning: This is only for practice!!! 
# Do not upload any certification or password in real environments!!!
ENV PGADMIN_DEFAULT_EMAIL=admin@admin.com
ENV PGADMIN_DEFAULT_PASSWORD=pass
EXPOSE 80