FROM postgres:12.12
# Set environmental variables for the username and the password
# Warning: This is only for practice!!! 
# Do not upload any certification or password in real environments!!!
ENV POSTGRES_USER=root
ENV POSTGRES_PASSWORD=thisispassword
# Create a database called web
ENV POSTGRES_DB=web
EXPOSE 5432